// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9isPB3QVgZV49v3wmgGzZRVLvDkAmCyM',
    appId: '1:121672952940:android:50a9613253316eb10dbc49',
    messagingSenderId: '121672952940',
    projectId: 'fir-test-push-c7d32',
    storageBucket: 'fir-test-push-c7d32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_xAoYBvQsxYr4sCl35lUu6dzCZ5lIBIo',
    appId: '1:121672952940:ios:9dd84067517aa64d0dbc49',
    messagingSenderId: '121672952940',
    projectId: 'fir-test-push-c7d32',
    storageBucket: 'fir-test-push-c7d32.appspot.com',
    iosClientId: '121672952940-jfb15fl8fi2imlgfgl5lh2h7seun2425.apps.googleusercontent.com',
    iosBundleId: 'masli.prof.firebasePush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_xAoYBvQsxYr4sCl35lUu6dzCZ5lIBIo',
    appId: '1:121672952940:ios:b3b6e9035cb8ed320dbc49',
    messagingSenderId: '121672952940',
    projectId: 'fir-test-push-c7d32',
    storageBucket: 'fir-test-push-c7d32.appspot.com',
    iosClientId: '121672952940-eif3330hcrprtlncnqi6iaepsarm8oph.apps.googleusercontent.com',
    iosBundleId: 'masli.prof.firebasePush.RunnerTests',
  );
}
